openapi: 3.0.1
info:
  title: LedWall REST Plugin - API Definition
  description: This is the API definition, implemented by the ledwall-rest-plugin. Using this API you are able to control a LedWall by the HTTP protocol. The main purpose of this API is to connect the [AElite](https://ae-lite.github.io) application to LedWall devices.
  version: 1.0.0
paths:
  /:
    get:
      tags:
        - "LedWall"
      summary: General informations about the device
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
components:
  schemas:
    Device:
      type: object
      properties:
        type:
          type: string
          default: "io.aelite.ledwall.core.LedWall"
        width:
          type: integer
          description: LedWall width in pixels
        height:
          type: integer
          description: LedWall height in pixels
